package com.martin.studygreendao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.ds.greendaobean.MyDateBean;

import com.martin.studygreendao.greendao.MyDateBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myDateBeanDaoConfig;

    private final MyDateBeanDao myDateBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myDateBeanDaoConfig = daoConfigMap.get(MyDateBeanDao.class).clone();
        myDateBeanDaoConfig.initIdentityScope(type);

        myDateBeanDao = new MyDateBeanDao(myDateBeanDaoConfig, this);

        registerDao(MyDateBean.class, myDateBeanDao);
    }
    
    public void clear() {
        myDateBeanDaoConfig.clearIdentityScope();
    }

    public MyDateBeanDao getMyDateBeanDao() {
        return myDateBeanDao;
    }

}
